### ISSUE TITLE
No space left on device with docker

### ISSUE THREAD

**Issue by Hermanverschooten** [coreos/coreos-xhyve#14]
When I try to run one of my docker-composed containers I quickly run out of space.
I see the _disk_ is currently only 512Mb, is there a way to increase this?

**Comment by AntonioMeireles** [comment]
@Hermanverschooten 
(long story short) go along something like ...
- Create a virtual hard disk image (16 GB below)
  `dd if=/dev/zero of=extra.img bs=1G count=16`
- add to `coreos-xhyve-run`  after the `LPC_DEV` line ...
  `IMG_HDD="-s 4,virtio-blk,extra.img"`
- then just follow https://coreos.com/docs/cluster-management/setup/mounting-storage/

should work...

**Comment by rimusz** [comment]
@AntonioMeireles I already tried that way, coreos just crashes on the boot

**Comment by AntonioMeireles** [comment]
@rimusz i didn't have too much time to look (busy atm) but, at sight, i suspect that masking the lvm services _may_  do the trick ... (lvm2-{lvmetad,monitor,pvscan@}) as are them that seem to be messing with this.

**Comment by rimusz** [comment]
@AntonioMeireles no worries, as I do not have much time to play with it too.
I just gave a shot

**Comment by jbergstroem** [comment]
Just tried this as well. Stops while trying to start udev on boot.

**Comment by AntonioMeireles** [comment]
@jbergstroem it works (tested with tip (built from source) xhyve).
_trick_ is to just format the volume in advance ...
- dd if=/dev/zero of=extra.img bs=1G count=16
- mkfs.ext4 -L whateverLabel extra.img

**Comment by jbergstroem** [comment]
Ah, obviously. Now to conveniently doing that on a mac :)

**Comment by AntonioMeireles** [comment]
`brew install e2fsprogs` :smiley:

**Comment by jbergstroem** [comment]
Thanks man, now I feel slightly RTFM'ed!

**Comment by jbergstroem** [comment]
..actually, it still freezes:

``` bash
$ /usr/local/opt/e2fsprogs/sbin/fsck.ext4 ~/vm/coreos/extra.img
e2fsck 1.42.12 (29-Aug-2014)
coreos-extra: clean, 11/1048576 files, 109841/4194304 blocks
$ sudo MEMORY=2048 IMG_HDD="-s 4,virtio-blk,/Users/jbergstroem/vm/coreos/extra.img" \
       SSHKEY="$(cat ~/.ssh/foo.pub)" ./coreos-xhyve-run
<snip>
[  OK  ] Started Rebuild Dynamic Linker Cache.
[  OK  ] Started Rebuild Hardware Database.
         Starting udev Coldplug all Devices...
[  OK  ] Started udev Coldplug all Devices.
         Starting udev Wait for Complete Device Initialization...
[  OK  ] Found device /dev/ttyS0.
[  *** ] A start job is running for udev Wai...vice Initialisation (59s / 3min)./coreos-xhyve-run: line 46: 92205 Killed: 9  
```

I've tried the beta channel to no avail.

**Comment by AntonioMeireles** [comment]
@jbergstroem humm, are you using a xhyve binary built from a xhyve git tip checkout (and not the one, right now, in homebrew) ?

**Comment by jbergstroem** [comment]
`brew install --head xhyve`

**Comment by AntonioMeireles** [comment]
edit **coreos-xhyve-run** and in **CMDLINE** cut `acpi=off` and try again plz. (that one is not yet merged - it's part of #34)

**Comment by jbergstroem** [comment]
..and I'm in. Thanks, again @AntonioMeireles.

**Comment by AntonioMeireles** [comment]
great to hear! thanks to you for your patience!

**Comment by rimusz** [comment]
@AntonioMeireles @jbergstroem  no needs to pre-format the extra.img with `e2fsprogs`.
I use `format-ephemeral.service` to check if the `/dev/vda` is formatted, if not it gets formatted.
This is the snippet from my user-data:

```
...
    - name: fleet.service
      command: start
    - name: format-ephemeral.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/sh -c '/usr/sbin/blkid -pi /dev/vda | grep TYPE= || /usr/sbin/mkfs.ext4 /dev/vda'
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /var/lib/docker
        Requires=format-ephemeral.service
        After=format-ephemeral.service
        Before=docker.service
        [Mount]
        What=/dev/vda
        Where=/var/lib/docker
        Type=ext4
    - name: docker-tcp.socket
...
```
