### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by luebken** [coreos/coreos-xhyve#8]
I'm trying to get this running. `xhyve` runs. But what is the expected out put from `./coreos-xhyve-fetch` Mine is empty. Any pointers for debugging it?

This is the output from `sudo ./coreos-xhyve-run` BTW:

```
kexec: failed to load kernel imgs/coreos_production_pxe.vmlinuz
                                                               ./coreos-xhyve-run: line 17:  3764 Abort trap: 6           xhyve $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_HDD -f kexec,imgs/$VMLINUZ,imgs/$INITRD,"$CMDLINE"
```

**Comment by rimusz** [comment]
I see that too on the first run, running the second time it works

**Comment by c4milo** [comment]
@luebken you are probably missing GPG or CURL.

**Comment by luebken** [comment]
It's a bash-script. Duuh. Thanks. Sorry.
